#' Retrieves DAM2 data from one or several continuous files
#'
#' Uses a query mechanism to get data from a DAM2 array.
#' This is useful when using the default behaviour of TriKinetics software
#' where data is simply appended to a single long file per monitor.
#'
#' @param query [data.table] representing a formatted query used to request data (see detail).
#' @param FUN function (optional) to transform the data from each animal
#' immediately after is has been loaded.
#' @param ... extra arguments to be passed to `FUN`
#' @return A [behavr] table.
#' The metadata contains all the query columns and an autogenerated id per animal.
#' The data has the columns:
#' * `id` -- autogenerated unique identifier, one per animal
#' *  `t` -- time
#' * `activity` -- number of beam crosses
#' @details `query` must be a [data.frame] (or [data.table]) object.
#' Conceptually, each row of the query describes one animal with one set of conditions (when `region_id` is specified),
#' or in each monitor (when it is not).
#' It must have  the following columns:
#' * `path` -- the location of a data file (e.g. "C:/User/me/Desktop/Monitor3.txt").
#' * `start_datetme` -- the first day and time of the requested experiment (e.g. "2014-12-28 18:00:00").
#' * `stop_datetime` -- the last day and time of the requested experiment (e.g. "2014-12-30  19:00:00" or simply "2014-12-30").
#' * `region_id` -- the channel (between 1 and 32) in which the animal was in (e.g. "20").
#'   `region_id` is optional. If not provided, all 32 channels are loaded *with the same conditions*.
#' * `???` *any number of arbitrary columns* to associate `conditions`/`treatments`/`genotypes`/... to the previous columns.
#'
#' The time in data is expressed relatively to start_date.
#' In other words, if you do circadian analysis, and your D-L transitions are at 10:00:00, you want to set
#' `start_datetime = "YYY-MM-DD 10:00:00"`.
#' @examples
#' sample_file <- damr_example("M064.txt")
#' query = data.table::data.table(path=sample_file,
#'                     # note the time (10:00) is added as reference time
#'                     start_datetime = c("2017-07-01 10:00:00", "2017-07-02 10:00:00"),
#'                     stop_datetime = "2017-07-07",
#'                     region_id=c(1:32),
#'                     condition=rep(letters[1:2],each=16),
#'                     genotype=c("A", "A", "B", "B"))
#'
#' dt <- query_dam2(query)
#' print(dt)
#' # genotype was added to our metadata:
#' print(dt[meta=TRUE])
#' # Just the first few reads, we run head() on each animal
#' dt <- query_dam2(query, FUN=head)
#' print(dt)
#' @seealso [read_dam2_file] to to load data from a single file (without a query).
#' @export
query_dam2 <- function(query, FUN=NULL, ...){
  tz="UTC"
  q <- data.table::copy(data.table::as.data.table(query))
  cn <- colnames(q)
  if(!("path" %in% cn & "start_datetime" %in% cn & "stop_datetime" %in% cn )){
    stop("query MUST have at least thre columns names `path`, `start_datetime` and `stop_datetime`")
  }


  q[,experiment_id:=sprintf("%s|%s",
                 start_datetime,
                 basename(path))]
  # we expand query for all channels if no channel provided
  if(!"region_id" %in% cn)
    q <- q[q[,.(region_id=1:32),by=experiment_id], on="experiment_id"]

  q[,id:=sprintf("%02d|%s",
                 region_id,
                 experiment_id)]
  # TODO check for uniqueness in query!!
  to_read <- q[,.(regions = list(region_id)),by=c("path","start_datetime","stop_datetime")]
  s <- to_read[,
               list(data=list(damr:::read_dam2_file(path,
                                                    regions[[1]],
                                                    start_datetime,
                                                    stop_datetime,
                                                    tz=tz)
                              )
                    ),
               by="path,start_datetime,stop_datetime"]

  d <- behavr::bind_behavr_list(s[,data])

  # new metadata had the columns in q that are not in metadata already

  met <- d[meta=T]
  met <- met[
    q[,
      c("id", setdiff(colnames(q[,-"path"]), colnames(met))),
      with=F],
    on="id"]

  # replace metadata
  behavr::setmeta(d, met)
  if(!is.null(FUN))
    d <- d[,FUN(.SD, ...),by="id"]
  d
}
